name: go_you_travels
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.13.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cached_network_image: ^4.0.4
  flutter_screenutil: ^5.9.3
  flutter_riverpod: ^3.4.3
  flutter_hooks: ^0.21.3+1
  hooks_riverpod: ^3.4.3
  fluttertoast: ^10.0.0
  flutter_animate: ^4.5.2
  dio: ^5.11.1
  shimmer: ^4.0.0
  get_storage: ^2.1.1
  google_fonts: ^9.0.0
  lucide_icons_flutter: ^3.1.21
  carousel_slider: ^5.1.2
  go_router: ^18.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/logo/
